
output "ec2-public-dns" {
    value = aws_instance.public-ec2.public_dns
}

output "ec2-public-ip" {
    value = aws_instance.public-ec2.public_ip
}

output "ec2-public-private-dns" {
    value = aws_instance.public-ec2.private_dns
}

output "ec2-public-private-ip" {
    value = aws_instance.public-ec2.private_ip
}

output "db-address_src_old" {
    value = aws_db_instance.src_old.address
}

output "db-arn_src_old" {
    value = aws_db_instance.src_old.arn
}

output "db-domain_src_old" {
    value = aws_db_instance.src_old.domain
}

output "db-endpoint_src_old" {
    value = aws_db_instance.src_old.endpoint
}

output "db-hosted_zone_id_src_old" {
    value = aws_db_instance.src_old.hosted_zone_id
}

output "db-id_src_old" {
    value = aws_db_instance.src_old.id
}

output "db-name_src_old" {
    value = aws_db_instance.src_old.name
}

output "db-port_src_old" {
    value = aws_db_instance.src_old.port
}

output "db-address_dst_new" {
    value = aws_db_instance.dst_new.address
}

output "db-arn_dst_new" {
    value = aws_db_instance.dst_new.arn
}

output "db-domain_dst_new" {
    value = aws_db_instance.dst_new.domain
}

output "db-endpoint_dst_new" {
    value = aws_db_instance.dst_new.endpoint
}

output "db-hosted_zone_id_dst_new" {
    value = aws_db_instance.dst_new.hosted_zone_id
}

output "db-id_dst_new" {
    value = aws_db_instance.dst_new.id
}

output "db-name_dst_new" {
    value = aws_db_instance.dst_new.name
}

output "db-port_dst_new" {
    value = aws_db_instance.dst_new.port
}

output "ssh_key" {
  description = "Key-pair generated by Terraform"
  sensitive   = true
  value       = tls_private_key.dev_key.private_key_pem
}
